# 深度内部计划源: v23 测试、v20、每晚构建源
#   https://proposed-packages.deepin.com/
# 深度官方 北外 镜像源
#   https://mirrors.bfsu.edu.cn/deepin
# 北外源: debain/ubuntu/ubuntu-ports
#   https://mirrors.bfsu.edu.cn/
# 麒麟源
#   https://archive.kylinos.cn/kylin
# 龙芯源
#   http://pkg.loongnix.cn

mirrors = {
    'https://proposed-packages.deepin.com/': {
        'beige-testing': [
            'unstable'
        ],
        'dde-apricot': [
            'apricot',
            'unstable'
        ],
        'dde-nightly': [
            'bullseye',
            'dde-bullseye',
            'deepin-bullseye',
            'deepin-wine',
        ],
    },
    'https://mirrors.bfsu.edu.cn/deepin': {
        'apricot': [
            'apricot'
        ],
        'beige': [
            'beige'
        ],
    },
    'https://mirrors.bfsu.edu.cn/': {
        'debian': [
            'Debian12.2',
            'Debian11.8',
            'Debian10.13',
            'bookworm',
            'bookworm-backports',
            'bookworm-backports-sloppy',
            'bookworm-proposed-updates',
            'bookworm-updates',
            'bullseye',
            'bullseye-backports',
            'bullseye-backports-sloppy',
            'bullseye-proposed-updates',
            'bullseye-updates',
            'buster',
            'buster-backports',
            'buster-backports-sloppy',
            'buster-proposed-updates',
            'buster-updates',
            'experimental',
            'oldoldstable',
            'oldoldstable-backports',
            'oldoldstable-backports-sloppy',
            'oldoldstable-proposed-updates',
            'oldoldstable-updates',
            'oldstable',
            'oldstable-backports',
            'oldstable-backports-sloppy',
            'oldstable-proposed-updates',
            'oldstable-updates',
            'proposed-updates',
            'rc-buggy',
            'sid',
            'stable',
            'stable-backports',
            'stable-backports-sloppy',
            'stable-proposed-updates',
            'stable-updates',
            'testing',
            'testing-backports',
            'testing-proposed-updates',
            'testing-updates',
            'trixie',
            'trixie-backports',
            'trixie-proposed-updates',
            'trixie-updates',
            'unstable',
        ],
        'ubuntu': [
            'bionic',
            'bionic-backports',
            'bionic-proposed',
            'bionic-security',
            'bionic-updates',
            'devel',
            'devel-backports',
            'devel-proposed',
            'devel-security',
            'devel-updates',
            'focal',
            'focal-backports',
            'focal-proposed',
            'focal-security',
            'focal-updates',
            'jammy',
            'jammy-backports',
            'jammy-proposed',
            'jammy-security',
            'jammy-updates',
            'lunar',
            'lunar-backports',
            'lunar-proposed',
            'lunar-security',
            'lunar-updates',
            'mantic',
            'mantic-backports',
            'mantic-proposed',
            'mantic-security',
            'mantic-updates',
            'noble',
            'noble-backports',
            'noble-proposed',
            'noble-security',
            'noble-updates',
            'trusty',
            'trusty-backports',
            'trusty-proposed',
            'trusty-security',
            'trusty-updates',
            'xenial',
            'xenial-backports',
            'xenial-proposed',
            'xenial-security',
            'xenial-updates',
        ]
        ,
        'ubuntu-ports': {
            'bionic',
            'bionic-backports',
            'bionic-proposed',
            'bionic-security',
            'bionic-updates',
            'devel',
            'devel-backports',
            'devel-proposed',
            'devel-security',
            'devel-updates',
            'focal',
            'focal-backports',
            'focal-proposed',
            'focal-security',
            'focal-updates',
            'jammy',
            'jammy-backports',
            'jammy-proposed',
            'jammy-security',
            'jammy-updates',
            'lunar',
            'lunar-backports',
            'lunar-proposed',
            'lunar-security',
            'lunar-updates',
            'mantic',
            'mantic-backports',
            'mantic-proposed',
            'mantic-security',
            'mantic-updates',
            'noble',
            'noble-backports',
            'noble-proposed',
            'noble-security',
            'noble-updates',
            'trusty',
            'trusty-backports',
            'trusty-proposed',
            'trusty-security',
            'trusty-updates',
            'xenial',
            'xenial-backports',
            'xenial-proposed',
            'xenial-security',
            'xenial-updates',
        }
    },
    'https://archive.kylinos.cn/kylin/': {
        'KYLIN-ALL': [
            '10.0',
            '10.0-2101-KCM',
            '10.0-210507-yun-SZSW',
            '10.0-fixs',
            '10.0-jxsw',
            '10.0-zyj',
            '10.1',
            '10.1-0820-2',
            '10.1-2107-990-DKY',
            '10.1-2107-DKY',
            '10.1-2107-hwe-updates',
            '10.1-2107-updates',
            '10.1-2203-990-CCB',
            '10.1-2203-990-ZYD',
            '10.1-2203-CCB',
            '10.1-2203-LT',
            '10.1-2203-general-edu-updates',
            '10.1-2203-hwe-LT',
            '10.1-2203-hwe-general-edu-updates',
            '10.1-2203-hwe-updates',
            '10.1-2203-hwe-updates-preview',
            '10.1-2203-oem-hw-9006c-activation',
            '10.1-2203-oem-hw-990-activation',
            '10.1-2203-updates',
            '10.1-2203-updates-preview',
            '10.1-2209-hwe-pp-updates',
            '10.1-2209-hwe-updates',
            '10.1-2209-updates',
            '10.1-2303-XHS',
            '10.1-2303-hwe-pp-updates',
            '10.1-2303-hwe-pp-updates-preview',
            '10.1-2303-hwe-updates',
            '10.1-2303-hwe-updates-preview',
            '10.1-2303-oem-kmre',
            '10.1-2303-updates',
            '10.1-2303-updates-pre',
            '10.1-2303-updates-preview',
            '10.1-2304-tablet-updates',
            '10.1-2306-gf',
            '10.1-W525-2303-feature-preview',
            '10.1-ekylin',
            '10.1-embedded',
            '10.1-embedded-ctyun',
            '10.1-embedded-rockchip',
            '10.1-embedded-update',
            '10.1-gb18030-2022-font',
            '10.1-hwe',
            '10.1-hwe-oem-dell',
            '10.1-kirin9006C-2303-feature',
            '10.1-kirin9006C-2303-feature-preview',
            '10.1-kirin9006C-feature',
            '10.1-kirin9006C-feature-preview',
            '10.1-kirin990-2203u2-oem-hw',
            '10.1-kirin990-2303-feature',
            '10.1-kirin990-2303-feature-preview',
            '10.1-kirin990-feature',
            '10.1-kirin990-feature-preview',
            '10.1-kirinM900-2303-feature-preview',
            '10.1-kv',
            '10.1-la64',
            '10.1-oem-hp',
            '10.1-pv',
            '10.1-pw',
            '10.1-rk3588',
            '10.1-sm',
            '10.1-sw64',
            '10.1-vkylin',
            '10.1-wayland-2203-fix-disk',
            '10.1-wayland-2203-panguw',
            '10.1-wayland-2203-updates',
            '10.1-wayland-2203-updates-preview',
            '10.1-wayland-2303-updates',
            '10.1-wayland-2303-updates-preview',
            '4.0.2',
            '4.0.2-desktop',
            '4.0.2-server',
            '4.0.2sp1',
            '4.0.2sp1-desktop',
            '4.0.2sp1-server',
            '4.0.2sp2',
            '4.0.2sp2-desktop',
            '4.0.2sp2-server',
            '4.0.2sp2-server-ft2000',
            '4.0.2sp3',
            '4.0.2sp3-desktop',
            '4.0.2sp3-server',
            '4.0.2sp4',
            '4.0.2sp4-desktop',
            '4.0.2sp4-server',
            'Intel-Edu',
            'V10-GFB-020',
            'developer-kits',
        ]
    },
    'http://pkg.loongnix.cn/': {
        'loongnix': [
            'DaoXiangHu-cartoons',
            'DaoXiangHu-embedded',
            'DaoXiangHu-stable',
            'DaoXiangHu-testing',
            'DaoXiangHu-thirdparty',
        ],
        'loongnix-server' : [
            '8.3',
            '8.4',
        ]
    },
    'https://packages.microsoft.com/repos': {
        'edge': [
            'stable'    
        ]
    }
}